version: '3.4'

services:
  safaricom:
    image: ${DOCKER_REGISTRY-}safaricom
    build:
      context: .
      dockerfile: Dockerfile
  sqldb:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "Abcd@1234"
        ports:
            - "1433:1433"  
